### ISSUE TITLE
No rule to make target 'TestVectors/ocb.txt', needed by 'all-am'.  Stop.

### ISSUE THREAD

**Issue by minnyres** [noloader/cryptopp-autotools#5]
I get this error when I use autotools to build cryptopp 8.6.0 on openSUSE.

First, I extract the source and generate the configure script:
```
mkdir cryptopp
cd cryptopp
7z x ../cryptopp860.zip

tar -xf ../cryptopp-autotools-CRYPTOPP_8_6_0.tar.gz
cp  cryptopp-autotools-CRYPTOPP_8_6_0/* .
mkdir -p "$PWD/m4/"

autoupdate
libtoolize --force --install
autoreconf --force --install
```
Then I configure and build the project
```
CPPFLAGS="-DNDEBUG" CXXFLAGS="-g2 -O3" ./configure --prefix=$BUILDDIR/cryptopp  --enable-shared=no --enable-static
make
```
Although the library and cryptest is built successfully, `make` ends with the following error. It seems related to the test. Does the autotools supports to only install the library and skip the test?

> libtool: link: ranlib .libs/libcryptopp.a
> libtool: link: ( cd ".libs" && rm -f "libcryptopp.la" && ln -s "../libcryptopp.la" "libcryptopp.la" )
> /bin/sh ./libtool  --tag=CXX   --mode=link g++ -pthread -fdata-sections -ffunction-sections  -DCRYPTOPP_DATA_DIR='"/cryptopp/share/cryptopp/"' -g2 -O3 -pthread -Wl,--gc-sections -Wl,--build-id -Wl,--demangle -Wl,--exclude-libs,ALL -Wl,--as-needed  -o cryptest cryptest-test.o cryptest-bench1.o cryptest-bench2.o cryptest-bench3.o cryptest-datatest.o cryptest-dlltest.o cryptest-fipsalgt.o cryptest-validat0.o cryptest-validat1.o cryptest-validat2.o cryptest-validat3.o cryptest-validat4.o cryptest-validat5.o cryptest-validat6.o cryptest-validat7.o cryptest-validat8.o cryptest-validat9.o cryptest-validat10.o cryptest-regtest1.o cryptest-regtest2.o cryptest-regtest3.o cryptest-regtest4.o cryptest-adhoc.o libcryptopp.la
> libtool: link: g++ -pthread -fdata-sections -ffunction-sections -DCRYPTOPP_DATA_DIR=\"/cryptopp/share/cryptopp/\" -g2 -O3 -pthread -Wl,--gc-sections -Wl,--build-id -Wl,--demangle -Wl,--exclude-libs -Wl,ALL -Wl,--as-needed -o .libs/cryptest cryptest-test.o cryptest-bench1.o cryptest-bench2.o cryptest-bench3.o cryptest-datatest.o cryptest-dlltest.o cryptest-fipsalgt.o cryptest-validat0.o cryptest-validat1.o cryptest-validat2.o cryptest-validat3.o cryptest-validat4.o cryptest-validat5.o cryptest-validat6.o cryptest-validat7.o cryptest-validat8.o cryptest-validat9.o cryptest-validat10.o cryptest-regtest1.o cryptest-regtest2.o cryptest-regtest3.o cryptest-regtest4.o cryptest-adhoc.o  ./.libs/libcryptopp.so -pthread -Wl,-rpath -Wl,/cryptopp/lib64
> make[1]: *** No rule to make target 'TestVectors/ocb.txt', needed by 'all-am'.  Stop.
> make[1]: Leaving directory '/home/cat/git/amule-win32/src/cryptopp'
> make: *** [Makefile:1271: all] Error 2

**Comment by noloader** [comment]
Thanks @minnyres,

Damn, that is there:

```
$ cat Makefile.am | grep ocb
        TestVectors/ocb.txt               TestVectors/vmac.txt \
```

Delete it, please. I have not checked-in OCB mode yet.

I'll push the change, but it won't help you with the 8.6 release.

**Comment by noloader** [comment]
Should be cleared at [Commit 9fc225774a12](https://github.com/noloader/cryptopp-autotools/commit/9fc225774a12).
