### ISSUE TITLE
Missing libpowerX_ppc_la_SOURCES in Makefile.am

### ISSUE THREAD

**Issue by aakodadi** [noloader/cryptopp-autotools#7]
For `X = {7, 8, 9}`, there are missing `libpowerX_ppc_la_SOURCES` variables in the Automake script. This makes `make dist` fails because by default the generated `Makefile` tries to look for `libpowerX_ppc.cpp` while the actual cpp file names are `powerX_ppc.cpp`.

**Comment by noloader** [comment]
Thanks @aakodadi. I merged the PR.

I sent you an invite to be a collaborator. The idea is, if I get hit by a bus, then this project can go on without me...

**Comment by aakodadi** [comment]
Roger that @noloader, I hope that nothing bad happens to you tho
